apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: e80fba85-48a1-4d97-958e-1e0408269d4e
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: fn-get-marital-status
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /enum/marital_status
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /enum/marital_status
